### ISSUE TITLE
User installed fonts do not seem to work

### ISSUE THREAD

**Issue by Lazza** [valerioa/Inkscape-MacOS-Curated-Build#15]
I installed Lato and Raleway by dragging them in the Font Book. I was using both of them with [a previous version of Inkscape](https://inkscape.org/en/~su_v/galleries/osxmenu-r12922/) (_osxmenu r12922_) and they worked quite well.

Your build does not seem to pick them up.

**Comment by valerioa** [comment]
I'm closing this one. Please try the new release and re-open, or open a new one as needed.

**Comment by rteest53** [comment]
valerio,
i copied fonts to the
/applications/inkscape.app/contents/resources/share/fonts directory and
have no problems using the fonts.

i am using the current v2 0.9.23 and the "about inkscape" splash screen
shows version 0.9.22.2 artwork. thought i would bring this to your
attention, unless this is intentional.

thanks for all your work.

best,
dwain alford

**Comment by Rastafabisch** [comment]
This is still an issue. 
Fonts installed at `~/Library/Fonts` are not taken into account. While someone can easily workaround this issue, I think also the fonts installed there should be taken into account by default.

**Comment by rteest53** [comment]
currently i have my fonts installed (copied) at:
/Applications/Inkscape.app/Contents/Resources/Share/Fonts and the current
build reads the fonts. i have been doing this since i found this mac
version of inkscape. i tried the other font folders in the program and
throughout the system, except for the system fonts folder where font book
installs fonts.

for development sake, would this solution be considered a workaround or
maybe a place to default install fonts?

best,
dwain

macbook pro, os x 10.12.6, inkscape 0.92.3.v2
