### ISSUE TITLE
Drag and drop files

### ISSUE THREAD

**Issue by rucativava** [valerioa/Inkscape-MacOS-Curated-Build#18]
Thank you so much for this work!
I've been using until yesterday https://code.launchpad.net/~suv-lp/inkscape/osxmenu which features a very handy feature: drag and drop from the Finder. This way I can drag an image file into Inkscape and it Imports it, or drag a file/folder into an Inkscape file dialog and it opens that folder, much like Finder does. If and when possible, it would be a great addition towards that "native" feeling (and design).

**Comment by paaguti** [comment]
+1

**Comment by valerioa** [comment]
The lack of drag and drop on the dock icon is due to a well know race condition between a starting app and the finder trying to immediately post an NSApplication OpenFile message to the message queue, after the app is started I'm working on solving the race condition.

Drag and drop conflicts with the ability to cut and paste vector files (pdf, svg, etc.) I will need to see if I can come up with a gtk+ patch that allows both. I will take time.

**Comment by rucativava** [comment]
You have my full support. At least in thoughts and prayers. :)

**Comment by rteest53** [comment]
i would like to again take the opportunity to thank you for your efforts
with inkscape for mac. i would compile source code if i knew how. i'm not
sure what i could do to assist the project, but my energy is definitely
committed to the project and is definitely positive. keep up the good work.

best,
dwain

**Comment by valerioa** [comment]
Since the release of Inkscape 1.0, and following versions, this project has no reason to exist anymore. Inkscape 1.0 (Inkscape 1.1.1 at the time of this writing - https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg ) is fully integrated with the Mac OSX UI. The 1.x.x Inkscape has Mac-style menus and window decorations. Granted, it is not perfect: the clipboard integration still has some problems (November 2021). However, Inkscape 1.x.x takes advantage of all the bugfixes and improvement that have been developed. I advise all to install the most recent version of Inkscape 1.x.x.
