### ISSUE TITLE
New Mac Discussion Channel for Inkscape

### ISSUE THREAD

**Issue by doctormo** [valerioa/Inkscape-MacOS-Curated-Build#23]
Development and packaging issues for Inkscape's Mac release are now being discussed in https://chat.inkscape.org/channel/mac-dev and since 2013, we've worked hard to recruit more people doing Mac work.

I don't know how well we can integrate the curated build yet. But I'm hoping that the new channel can act as an anchor for everyone who is invested in the Mac builds.

**Comment by valerioa** [comment]
Since the release of Inkscape 1.0, and following versions, this project has no reason to exist anymore. Inkscape 1.0 (Inkscape 1.1.1 at the time of this writing - https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg ) is fully integrated with the Mac OSX UI. The 1.x.x Inkscape has Mac-style menus and window decorations. Granted, it is not perfect: the clipboard integration still has some problems (November 2021). However, Inkscape 1.x.x takes advantage of all the bugfixes and improvement that have been developed. I advise all to install the most recent version of Inkscape 1.x.x.
