### ISSUE TITLE
'Inkscape quit unexpectedly'

### ISSUE THREAD

**Issue by kenaycock** [valerioa/Inkscape-MacOS-Curated-Build#24]
I'm attempting to run the latest release (Inkscape 0.92.3 gtk/quartz/macOS Integration v2
) on El Capitan (10.11.6), but Inkscape aborts before loading. Here's an excerpt from the error report:

> Dyld Error Message:
>   Symbol not found: _mkostemp
>   Referenced from: /Applications/Inkscape.app/Contents/Resources/lib/libfontconfig.1.dylib (which was built for Mac OS X 10.13)
>   Expected in: /usr/lib/libSystem.B.dylib

Is 10.13 required to run the latest release? Any possible workarounds?

**Edit:** I tried again with 0.92.2.quartz.v6 and it is running happily on 10.11.6

**Comment by rteest53** [comment]
i'm running 0.92.3 on sierra (10.12.6) works fine.

**Comment by valerioa** [comment]
Since the release of Inkscape 1.0, and following versions, this project has no reason to exist anymore. Inkscape 1.0 (Inkscape 1.1.1 at the time of this writing - https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg ) is fully integrated with the Mac OSX UI. The 1.x.x Inkscape has Mac-style menus and window decorations. Granted, it is not perfect: the clipboard integration still has some problems (November 2021). However, Inkscape 1.x.x takes advantage of all the bugfixes and improvement that have been developed. I advise all to install the most recent version of Inkscape 1.x.x.
