### ISSUE TITLE
Problem with CMake on Mac

### ISSUE THREAD

**Issue by InesSchneiderOAL** [valerioa/Inkscape-MacOS-Curated-Build#31]
there is no lipsoup 2.4 for I got the newer version of 3.0.2 and I dont find the command to change this. Using mac and homebrew.

**Comment by valerioa** [comment]
Hello Ines,

since Inkscape main line has released 1.0 and following versions, I have stopped maintaining this project. Inkscape 1.0 (as I am writing this the current version is 1.1.1 - https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg ) is fully integrated with the Mac OSX UI,  so there is no reason for this project anymore. The new Inkscape has Mac-style menus and windows. Granted, it is not perfect: the clipboard integration still has some problems. But, you also take advantage of all the bugfixes that have been developed since the 0.9x versions.

I suggest you give it a try:

https://inkscape.org/gallery/item/29282/Inkscape-1.1.1.dmg

Let me know,
Valerio
